sudo: required
language: python

env:
  global:
    - DOCKER_IMAGE=alectolytic/rpmbuilder
    - OS_ARCH=x86_64
  matrix:
    - OS_TYPE=centos OS_DIST=epel OS_VERSION=7
    - OS_TYPE=centos OS_DIST=epel OS_VERSION=6
services:
  - docker

install: true

script:
  # we want to test complete build, so we build final RPM (no -e "SRPM_ONLY=1" switch):
  - docker run -v ${PWD}:/sources -v ${PWD}:/output:Z ${DOCKER_IMAGE}:${OS_TYPE}-${OS_VERSION}
  - stat *.rpm
